// <auto-generated />
using System;
using CashierDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CashierDB.Migrations
{
    [DbContext(typeof(CashierContext))]
    [Migration("20230509152605_v1.8")]
    partial class v18
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CashierDB.Tables.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.ToTable("Company", (string)null);

                    b.HasData(
                        new
                        {
                            CompanyId = 1
                        });
                });

            modelBuilder.Entity("CashierDB.Tables.ItemType", b =>
                {
                    b.Property<int>("ItemTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemTypeId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemTypeId");

                    b.ToTable("ItemType", (string)null);

                    b.HasData(
                        new
                        {
                            ItemTypeId = 1,
                            Name = "Entree"
                        },
                        new
                        {
                            ItemTypeId = 2,
                            Name = "Drink"
                        },
                        new
                        {
                            ItemTypeId = 3,
                            Name = "Dessert"
                        });
                });

            modelBuilder.Entity("CashierDB.Tables.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuItemId"), 1L, 1);

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("MenuItemId");

                    b.HasIndex("ItemTypeId");

                    b.ToTable("MenuItem", (string)null);

                    b.HasData(
                        new
                        {
                            MenuItemId = 1,
                            ItemTypeId = 1,
                            Name = "Fried Chicken w/ Rice",
                            Price = 150f,
                            Stock = 25
                        },
                        new
                        {
                            MenuItemId = 2,
                            ItemTypeId = 1,
                            Name = "Ribs w/ Rice",
                            Price = 175f,
                            Stock = 25
                        },
                        new
                        {
                            MenuItemId = 3,
                            ItemTypeId = 1,
                            Name = "Sisig w/ Rice",
                            Price = 125f,
                            Stock = 25
                        },
                        new
                        {
                            MenuItemId = 4,
                            ItemTypeId = 2,
                            Name = "BTS Drink",
                            Price = 95f,
                            Stock = 50
                        },
                        new
                        {
                            MenuItemId = 5,
                            ItemTypeId = 2,
                            Name = "Sola",
                            Price = 99f,
                            Stock = 50
                        },
                        new
                        {
                            MenuItemId = 6,
                            ItemTypeId = 2,
                            Name = "Soft Drink in Can",
                            Price = 75f,
                            Stock = 50
                        },
                        new
                        {
                            MenuItemId = 7,
                            ItemTypeId = 3,
                            Name = "Cheesecake",
                            Price = 200f,
                            Stock = 20
                        },
                        new
                        {
                            MenuItemId = 8,
                            ItemTypeId = 3,
                            Name = "Moist Cake",
                            Price = 150f,
                            Stock = 20
                        },
                        new
                        {
                            MenuItemId = 9,
                            ItemTypeId = 3,
                            Name = "Sundae",
                            Price = 100f,
                            Stock = 20
                        });
                });

            modelBuilder.Entity("CashierDB.Tables.OrderList", b =>
                {
                    b.Property<int>("OrderListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderListId"), 1L, 1);

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOld")
                        .HasColumnType("bit");

                    b.Property<bool>("IsServed")
                        .HasColumnType("bit");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<float>("RealTotal")
                        .HasColumnType("real");

                    b.Property<int>("ServedQuantity")
                        .HasColumnType("int");

                    b.Property<int>("TabId")
                        .HasColumnType("int");

                    b.Property<float>("Total")
                        .HasColumnType("real");

                    b.HasKey("OrderListId");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("TabId");

                    b.ToTable("OrderList", (string)null);
                });

            modelBuilder.Entity("CashierDB.Tables.PriceModifier", b =>
                {
                    b.Property<int>("PriceModifierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceModifierId"), 1L, 1);

                    b.Property<bool>("IsAdd")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSpecial")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Percentage")
                        .HasColumnType("int");

                    b.HasKey("PriceModifierId");

                    b.ToTable("PriceModifier", (string)null);
                });

            modelBuilder.Entity("CashierDB.Tables.PriceModifiersApplied", b =>
                {
                    b.Property<int>("PriceModifiersAppliedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceModifiersAppliedId"), 1L, 1);

                    b.Property<int>("PriceModifierId")
                        .HasColumnType("int");

                    b.Property<int>("TabId")
                        .HasColumnType("int");

                    b.Property<float>("Total")
                        .HasColumnType("real");

                    b.HasKey("PriceModifiersAppliedId");

                    b.HasIndex("PriceModifierId");

                    b.HasIndex("TabId");

                    b.ToTable("PriceModifiersApplied", (string)null);
                });

            modelBuilder.Entity("CashierDB.Tables.Tab", b =>
                {
                    b.Property<int>("TabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TabId"), 1L, 1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClose")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTakeOut")
                        .HasColumnType("bit");

                    b.Property<float>("Tip")
                        .HasColumnType("real");

                    b.Property<float>("Total")
                        .HasColumnType("real");

                    b.HasKey("TabId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Tab", (string)null);
                });

            modelBuilder.Entity("CashierDB.Tables.MenuItem", b =>
                {
                    b.HasOne("CashierDB.Tables.ItemType", "ItemTypeLink")
                        .WithMany("MenuItems")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemTypeLink");
                });

            modelBuilder.Entity("CashierDB.Tables.OrderList", b =>
                {
                    b.HasOne("CashierDB.Tables.MenuItem", "MenuItemLink")
                        .WithMany("OrderLists")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CashierDB.Tables.Tab", "TabLink")
                        .WithMany("OrderLists")
                        .HasForeignKey("TabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItemLink");

                    b.Navigation("TabLink");
                });

            modelBuilder.Entity("CashierDB.Tables.PriceModifiersApplied", b =>
                {
                    b.HasOne("CashierDB.Tables.PriceModifier", "PriceModifierLink")
                        .WithMany("Tabs")
                        .HasForeignKey("PriceModifierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CashierDB.Tables.Tab", "TabLink")
                        .WithMany("PriceModifiers")
                        .HasForeignKey("TabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceModifierLink");

                    b.Navigation("TabLink");
                });

            modelBuilder.Entity("CashierDB.Tables.Tab", b =>
                {
                    b.HasOne("CashierDB.Tables.Company", "CompanyLink")
                        .WithMany("Tabs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyLink");
                });

            modelBuilder.Entity("CashierDB.Tables.Company", b =>
                {
                    b.Navigation("Tabs");
                });

            modelBuilder.Entity("CashierDB.Tables.ItemType", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("CashierDB.Tables.MenuItem", b =>
                {
                    b.Navigation("OrderLists");
                });

            modelBuilder.Entity("CashierDB.Tables.PriceModifier", b =>
                {
                    b.Navigation("Tabs");
                });

            modelBuilder.Entity("CashierDB.Tables.Tab", b =>
                {
                    b.Navigation("OrderLists");

                    b.Navigation("PriceModifiers");
                });
#pragma warning restore 612, 618
        }
    }
}
